import { Prestator, PachetEveniment, Testimonial } from "./types";

export const PRESTATORI: Prestator[] = [
  {
    id: "1",
    nume: "Alexandru Popescu",
    slug: "alexandru-popescu-barman",
    categorie: "barman",
    titlu: "Barman cu Bar Mobil",
    descriere: "Cu peste 8 ani de experiență în mixologie și evenimente premium, ofer servicii complete de bar mobil pentru nunți, petreceri corporate și evenimente private. Barul meu mobil include o selecție completă de băuturi premium, echipamente profesionale și o prezentare elegantă care se potrivește oricărui eveniment. Fiecare cocktail este preparat cu ingrediente de calitate și prezentat impecabil.",
    descriereScurta: "Barman profesionist cu bar mobil complet echipat pentru evenimente de excepție.",
    tipPret: "orar",
    pretDeLa: 200,
    unitatePret: "oră",
    imagini: ["/images/provider-barman-1.png", "/images/gallery-bar-setup-1.png", "/images/gallery-cocktails-1.png"],
    imagineCoperta: "/images/provider-barman-1.png",
    rating: 4.9,
    numarRecenzii: 127,
    locatie: "București",
    esteVerificat: true,
    estePromovat: true,
    experienta: "8+ ani",
    telefon: "+40 742 111 222",
    email: "alex.barman@email.com",
    pachete: [
      {
        id: "p1",
        nume: "Basic",
        descriere: "Ideal pentru petreceri mici și intime",
        pret: 1500,
        tipPret: "deLa",
        caracteristici: [
          "Bar mobil elegant",
          "1 barman profesionist",
          "Până la 50 invitați",
          "4 ore servicii",
          "Menu 10 cocktail-uri",
        ],
      },
      {
        id: "p2",
        nume: "Premium",
        descriere: "Pentru evenimente de dimensiuni medii",
        pret: 2500,
        tipPret: "deLa",
        caracteristici: [
          "Bar mobil premium cu LED",
          "2 barmani profesioniști",
          "Până la 150 invitați",
          "6 ore servicii",
          "Menu 20 cocktail-uri",
          "Show flair inclus",
        ],
        estePopular: true,
      },
      {
        id: "p3",
        nume: "All Inclusive",
        descriere: "Experiența completă pentru evenimente mari",
        pret: 4500,
        tipPret: "deLa",
        caracteristici: [
          "2 baruri mobile premium",
          "4 barmani profesioniști",
          "Număr nelimitat invitați",
          "8+ ore servicii",
          "Menu personalizat",
          "Show flair & molecular",
          "Băuturi premium incluse",
        ],
      },
    ],
  },
  {
    id: "2",
    nume: "Maria Ionescu",
    slug: "maria-ionescu-barman",
    categorie: "barman",
    titlu: "Barman & Mixologist",
    descriere: "Specializată în cocktail-uri artizanale și prezentări spectaculoase. Fiecare eveniment este o oportunitate de a crea experiențe memorabile pentru invitați.",
    descriereScurta: "Mixologist cu experiență în evenimente de lux și cocktail-uri signature.",
    tipPret: "orar",
    pretDeLa: 180,
    unitatePret: "oră",
    imagini: ["/images/provider-barman-2.png", "/images/gallery-cocktails-2.png"],
    imagineCoperta: "/images/provider-barman-2.png",
    rating: 4.8,
    numarRecenzii: 89,
    locatie: "București",
    esteVerificat: true,
    estePromovat: false,
    experienta: "6 ani",
  },
  {
    id: "3",
    nume: "Andrei Dumitrescu",
    slug: "andrei-dumitrescu-ospatar",
    categorie: "ospatar",
    titlu: "Ospătar Profesionist",
    descriere: "Oferim servicii de ospătărie de înaltă clasă pentru nunți și evenimente corporate. Echipa noastră este instruită în cele mai rafinate tehnici de servire.",
    descriereScurta: "Servicii de ospătărie elegantă pentru evenimente premium.",
    tipPret: "orar",
    pretDeLa: 100,
    unitatePret: "oră",
    imagini: ["/images/provider-ospatar-1.png", "/images/gallery-event-1.png"],
    imagineCoperta: "/images/provider-ospatar-1.png",
    rating: 4.7,
    numarRecenzii: 156,
    locatie: "București",
    esteVerificat: true,
    estePromovat: true,
    experienta: "10+ ani",
  },
  {
    id: "4",
    nume: "Elena Stanciu",
    slug: "elena-stanciu-ospatar",
    categorie: "ospatar",
    titlu: "Servicii Ospătărie",
    descriere: "Ospătărie profesională pentru evenimente de toate dimensiunile. Atenție la detalii și servicii impecabile garantate.",
    descriereScurta: "Echipă de ospătari profesioniști pentru orice tip de eveniment.",
    tipPret: "orar",
    pretDeLa: 90,
    unitatePret: "oră",
    imagini: ["/images/provider-ospatar-2.png"],
    imagineCoperta: "/images/provider-ospatar-2.png",
    rating: 4.6,
    numarRecenzii: 78,
    locatie: "Ilfov",
    esteVerificat: true,
    estePromovat: false,
    experienta: "5 ani",
  },
  {
    id: "5",
    nume: "Cristian Gheorghe",
    slug: "cristian-gheorghe-wine-corner",
    categorie: "wine-corner",
    titlu: "Wine Corner & Somelier",
    descriere: "Transformăm evenimentul dumneavoastră într-o experiență de degustare raffinată. Selecție de vinuri românești și internaționale premium.",
    descriereScurta: "Wine corner premium cu somelier și selecție de vinuri exclusive.",
    tipPret: "oferta",
    imagini: ["/images/provider-wine-1.png", "/images/gallery-event-2.png"],
    imagineCoperta: "/images/provider-wine-1.png",
    rating: 4.9,
    numarRecenzii: 45,
    locatie: "București",
    esteVerificat: true,
    estePromovat: true,
    experienta: "12 ani",
  },
  {
    id: "6",
    nume: "Coffee Masters",
    slug: "coffee-masters",
    categorie: "coffee-corner",
    titlu: "Coffee Corner Specialty",
    descriere: "Stație de cafea specialty cu barista profesionist. Preparăm cafea de specialitate direct la evenimentul dumneavoastră.",
    descriereScurta: "Coffee corner cu cafea specialty și latte art profesionist.",
    tipPret: "orar",
    pretDeLa: 150,
    unitatePret: "oră",
    imagini: ["/images/provider-coffee-1.png", "/images/provider-coffee-2.png"],
    imagineCoperta: "/images/provider-coffee-1.png",
    rating: 4.8,
    numarRecenzii: 67,
    locatie: "București",
    esteVerificat: true,
    estePromovat: false,
    experienta: "4 ani",
  },
  {
    id: "7",
    nume: "Latte Art Studio",
    slug: "latte-art-studio",
    categorie: "coffee-corner",
    titlu: "Coffee Corner Premium",
    descriere: "Echipamente profesionale La Marzocco și cafea de specialitate pentru evenimente de top.",
    descriereScurta: "Experiență premium de cafea cu echipamente profesionale.",
    tipPret: "oferta",
    imagini: ["/images/provider-coffee-2.png"],
    imagineCoperta: "/images/provider-coffee-2.png",
    rating: 5.0,
    numarRecenzii: 34,
    locatie: "București",
    esteVerificat: true,
    estePromovat: true,
    experienta: "7 ani",
  },
];

export const PACHETE_EVENIMENTE: PachetEveniment[] = [
  {
    id: "nunta-100",
    nume: "Pachet Nuntă 100 Persoane",
    descriere: "Pachetul ideal pentru nunți de dimensiuni medii. Include toate serviciile necesare pentru o experiență completă.",
    numarInvitati: "80-120 invitați",
    pretDeLa: 5500,
    servicii: [
      { categorie: "barman", cantitate: 2, descriere: "Barmani profesioniști cu bar mobil" },
      { categorie: "ospatar", cantitate: 4, descriere: "Ospătari în ținută elegantă" },
      { categorie: "cocktail-bar", cantitate: 1, descriere: "Bar cocktail-uri complet echipat" },
    ],
    economie: 800,
    imagine: "/images/gallery-event-1.png",
  },
  {
    id: "nunta-200",
    nume: "Pachet Nuntă 200 Persoane",
    descriere: "Soluția completă pentru nunți mari. Echipă extinsă și servicii premium pentru un eveniment de neuitat.",
    numarInvitati: "150-250 invitați",
    pretDeLa: 9500,
    servicii: [
      { categorie: "barman", cantitate: 4, descriere: "Barmani cu show flair" },
      { categorie: "ospatar", cantitate: 8, descriere: "Ospătari profesioniști" },
      { categorie: "cocktail-bar", cantitate: 2, descriere: "2 baruri mobile premium" },
      { categorie: "wine-corner", cantitate: 1, descriere: "Wine corner cu somelier" },
    ],
    economie: 1500,
    imagine: "/images/gallery-event-2.png",
  },
  {
    id: "corporate",
    nume: "Pachet Corporate",
    descriere: "Perfect pentru evenimente de firmă, lansări de produs sau team building-uri.",
    numarInvitati: "50-200 invitați",
    pretDeLa: 4000,
    servicii: [
      { categorie: "barman", cantitate: 2, descriere: "Barmani pentru cocktail party" },
      { categorie: "ospatar", cantitate: 4, descriere: "Ospătari în ținută formală" },
      { categorie: "coffee-corner", cantitate: 1, descriere: "Coffee corner specialty" },
    ],
    economie: 600,
    imagine: "/images/gallery-bar-setup-2.png",
  },
  {
    id: "petrecere-privata",
    nume: "Pachet Petrecere Privată",
    descriere: "Pentru aniversări, petreceri private sau evenimente intime.",
    numarInvitati: "30-80 invitați",
    pretDeLa: 2500,
    servicii: [
      { categorie: "barman", cantitate: 1, descriere: "Barman cu bar mobil" },
      { categorie: "ospatar", cantitate: 2, descriere: "Ospătari" },
    ],
    economie: 300,
    imagine: "/images/gallery-cocktails-1.png",
  },
];

export const TESTIMONIALE: Testimonial[] = [
  {
    id: "1",
    nume: "Ana & Mihai",
    rol: "Miri - Nuntă August 2024",
    continut: "Serviciile au fost impecabile! Barmanii au fost profesioniști, cocktail-urile delicioase, iar invitații noștri au fost încântați. Recomandăm cu căldură!",
    rating: 5,
    dataEveniment: "August 2024",
  },
  {
    id: "2",
    nume: "Raluca Marinescu",
    rol: "Event Manager - TechCorp",
    continut: "Am colaborat pentru lansarea de produs și totul a fost perfect organizat. Echipa a fost punctuală, profesionistă și foarte flexibilă cu cerințele noastre.",
    rating: 5,
    dataEveniment: "Octombrie 2024",
  },
  {
    id: "3",
    nume: "Ion & Maria",
    rol: "Miri - Nuntă Septembrie 2024",
    continut: "Bar-ul mobil a fost centrul atenției la nunta noastră! Show-ul de flair a impresionat pe toată lumea. Mulțumim pentru o seară de neuitat!",
    rating: 5,
    dataEveniment: "Septembrie 2024",
  },
  {
    id: "4",
    nume: "Andreea Popa",
    rol: "Organizator - Petrecere Aniversară",
    continut: "Am apelat la serviciile lor pentru aniversarea de 30 de ani. Cocktail-urile personalizate au fost spectaculoase! Cu siguranță vom mai colabora.",
    rating: 5,
    dataEveniment: "Noiembrie 2024",
  },
];

export function getPrestatorById(id: string): Prestator | undefined {
  return PRESTATORI.find((p) => p.id === id);
}

export function getPrestatorBySlug(slug: string): Prestator | undefined {
  return PRESTATORI.find((p) => p.slug === slug);
}

export function getPrestatoriByCategorie(categorie: string): Prestator[] {
  if (categorie === "toate" || !categorie) {
    return PRESTATORI;
  }
  return PRESTATORI.filter((p) => p.categorie === categorie);
}

export function getPrestatoriPromovati(): Prestator[] {
  return PRESTATORI.filter((p) => p.estePromovat);
}

